//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int RequestID { get; set; }
        public int Sender { get; set; }
        public int Reciever { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
